### ISSUE TITLE
tcp transport does not seem to work

### ISSUE THREAD

**Issue by dimichgh** [senecajs/seneca-mesh#40]
Hello,

As I understood the default protocol being used is http/web.
I am not sure if I am using correct parameters to override transport type or there is special way to configure balance client. 

So please let me know.

I tried this example (https://github.com/rjrodger/seneca-mesh/tree/master/examples/05-readme) to see if they work with tcp by using global option ```--seneca.options.transport.type=tcp```:
```
node color-service.js --seneca.options.transport.type=tcp
node color-client.js --seneca.options.transport.type=tcp
```
And I got an error:
```
2016-08-02T23:17:39.170Z 9wx044423wo2/1470179857112/31088/- ERROR	act	-       	OUT		-	1722	{format:hex,color:red}	ENTRY		-	seneca: No matching action pattern found for { format: 'hex', color: 'red' }, and no default result provided (using a default$ property).	act_not_found	{args:{ format: 'hex', color: 'red' },plugin:{}}	Error: seneca: No matching action pattern found for { format: 'hex', color: 'red' }, and no default result provided (using a default$ property).
    at Object.errormaker [as error] (/Users/dsemenov/Views/seneca-mesh/node_modules/seneca/node_modules/eraro/eraro.js:94:15)
    at Object.execute_action [as fn] (/Users/dsemenov/Views/seneca-mesh/node_modules/seneca/seneca.js:1102:25)
    at Immediate._onImmediate (/Users/dsemenov/Views/seneca-mesh/node_modules/seneca/node_modules/gate-executor/gate-executor.js:136:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

It works with default transport.

Thanks,
Dmytro

**Comment by dimichgh** [comment]
Looks like tcp transport on listening event here: 
https://github.com/senecajs/seneca-transport/blob/master/lib/tcp.js#L62-L65
should be like this
```
    listener.once('listening', function () {
      seneca.log.debug('listen', 'open', listenOptions)
      var clientOptions = seneca.util.deepextend(listenOptions, listener.address())
      return callback(null, clientOptions)
    })
```

**Comment by dimichgh** [comment]
Here's PR:
https://github.com/senecajs/seneca-transport/pull/107

**Comment by mihaidma** [comment]
thank you for the PR @dimichgh 
I'll allocate time to look over mesh and review your PR

**Comment by mihaidma** [comment]
i'll close this, the PR was merged. Preparing transport for publish
