### ISSUE TITLE
Quick Example doesn't work

### ISSUE THREAD

**Issue by Strandedpirate** [senecajs/seneca-mesh#57]
Trying to run the quick example on Windows 8.1 Pro and the client explodes with this error (the server started successfully with no errors):

```
D:\Git\seneca-test>node src/color-client.js
{"notice":"seneca: No matching action pattern found for { format: 'hex', color: 'red' }, and no default result provided (using a default$ property).",
"code":"act_not_found","err":{"eraro":true,"orig":null,"code":"act_not_found","seneca":true,"package":"seneca","msg":"seneca: No matching action patte
rn found for { format: 'hex', color: 'red' }, and no default result provided (using a default$ property).","details":{"args":"{ format: 'hex', color:
'red' }","plugin":{}},"callpoint":"at executable_action (D:\\Git\\seneca-test\\node_modules\\seneca\\seneca.js:1155:23)"},"msg":{"format":"hex","color
":"red"},"entry":true,"prior":[],"meta":{},"listen":false,"transport":{},"kind":"act","case":"ERR","duration":526,"level":"error","seneca":"it88c872hr
o3/1474354122861/412784/3.1.0/-","when":1474354123731}
{"msg":{"format":"hex","color":"red"},"entry":true,"prior":[],"meta":{},"listen":false,"transport":{},"kind":"act","case":"ERR","info":"seneca: Action
 undefined callback threw: Cannot read property 'color' of undefined.","code":"act_callback","err":{"eraro":true,"orig":{},"code":"act_callback","sene
ca":true,"package":"seneca","msg":"seneca: Action undefined callback threw: Cannot read property 'color' of undefined.","details":{"message":"Cannot r
ead property 'color' of undefined","instance":"Seneca/it88c872hro3/1474354122861/412784/3.1.0/-","orig$":{},"message$":"Cannot read property 'color' o
f undefined","plugin":{}},"callpoint":"at Seneca.<anonymous> (D:\\Git\\seneca-test\\src\\color-client.js:18:20)"},"duration":526,"level":"error","sene
ca":"it88c872hro3/1474354122861/412784/3.1.0/-","when":1474354123738}
```

**package.json below:**
```
{
  "name": "seneca-test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
  },
  "devDependencies": {
    "seneca": "^3.0.0",
    "seneca-balance-client": "^0.6.0",
    "seneca-mesh": "^0.9.0"
  }
}
```

Is there something special I need to do on a Windows machine?

**Comment by vishwasvadavi** [comment]
Hi @Strandedpirate. There is no issue with the package.json. Update your color-client.js file to encapsulate the act method inside the ready method.
Please use below snippet , hope it works

`
// color-client.js
var Seneca = require('seneca')

Seneca({log: 'test'})

  // load the mesh plugin
  .use('mesh')

  .ready( function () {

    var seneca = this

    // send a message out into the network
    // the network will know where to send format:hex messages
    seneca.act({format: 'hex', color: 'blue'}, function (err, out) {

      // prints #FF0000
      console.log(out.color)

      // disconnect from the network
      this.close()
    })
  })`

**Comment by Strandedpirate** [comment]
That did the trick. Thanks!
