### ISSUE TITLE
How to make service discovery across host's using seneca-mesh.?

### ISSUE THREAD

**Issue by mramakrushna** [senecajs/seneca-mesh#82]
I wrote the following, by copying the foo bar sample from git hub by adding IP's
1) base_ms just to act as base, hosted on machine host1 (can be any)

rama@Rama-vm:~/NodeJS/docker/ipc_net$ cat base_ms/base_ms.js 
var HOST = process.env.HOST || 'localhost'
 // Linux IP : 10.9.42.208 10.0.75.1
var mesh_opts = {
  base:true,
  host: '10.9.42.208'
}
require('seneca')()
  .use('mesh',mesh_opts)

2) bar_ms  hosted on machine host1 provides the service, and invokes the service from foo _ms
rama@Rama-vm:~/NodeJS/docker/ipc_net$ cat bar_ms/bar_ms.js 
require('seneca')()
  .add( 'bar:1', function (msg, done) {
    done( null, {x:1,v:100+msg.v} )
  })
// this service handles bar:1 messages
   .use('mesh', {
     auto:true,
     host: '10.9.42.208',          // host where service is hosted
     bases: ['10.9.42.208:3999'],  //location of Base Service
     listen:[
        {pin:'bar:1', host: '10.9.42.208'}
      ]
    })

  .ready( function () {
    var seneca = this
    setInterval( function() {
      // use foo:1, even though location of
      // service-foo is not configured!
      seneca.act('foo:1,v:2', console.log)
    }, 3000 )

  .listen({host:"localhost",port:"5000"});
  })

3) foo_ms hosted on host2, provides the service
$ cat foo_ms.js
require('seneca')()
  .add( 'foo:1', function (msg, done) {
              done( null, {x:1,v:100+msg.v} )
            })

// this service handles foo:1 messages
   .use('mesh', {
           auto:true,
           host: '10.9.42.181',             // host name , where this service is being hosted
           bases: ['10.9.42.208:3999'], // location of the base service
           listen:[
                      {pin:'foo:1', host: '10.9.42.181'}
                  ]
        })

-------------------------------------------------------
1) launch base service
rama@Rama-vm:~/NodeJS/docker/ipc_net$ docker run --network=host -it --name Base_MicroS base_ms:1.0.0

2) Launch the Foo Service,  
$ docker run -it --name Foo_MS1 --network=host foo_ms:1.0.0  bash
--------------------------------------------------------------------------
I find the error as below
Note:  settings related to firewall were changed so that I can ping the 
 Host IP from either of the host's to eachother successfully.
even from the docker container I could ping docker0 and HOST IP.(both directions host1=>host2 and viceversa)

I find issues launching foo_ms on my VM,. coming across below error
Seneca Fatal Error
==================
EXPOSE 56781
Message: seneca: listen EADDRNOTAVAIL 10.9.42.181:53478

Code: transport_listen

Details: { type: 'web',
  port: [Function],
  host: '10.9.42.181',
  path: '/act',
  protocol: 'http',
  timeout: 5555,
  max_listen_attempts: 11,
  attempt_delay: 222,
  serverOptions: {},
  pin: 'foo:1',
  model: 'consume',
  msgprefix: 'seneca_',
  callmax: 111111,
  msgidlen: 12,
  'orig$':
   { Error: listen EADDRNOTAVAIL 10.9.42.181:53478
       at Object.exports._errnoException (util.js:1033:11)
       at exports._exceptionWithHostPort (util.js:1056:20)
       at Server._listen2 (net.js:1263:19)
       at listen (net.js:1312:10)
       at doListening (net.js:1427:7)
       at _combinedTickCallback (internal/process/next_tick.js:83:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
     code: 'act_execute',
     errno: 'EADDRNOTAVAIL',
     syscall: 'listen',
     address: '10.9.42.181',
     port: 53478,
     eraro: true,
     orig:
      { Error: listen EADDRNOTAVAIL 10.9.42.181:53478

**Comment by alank64** [comment]
I'm having issues as well, but they might not be the same, however can I ask in your above example where you found "base:true..", is this a change or mistake?  I only found "isbase: true" ?

**Comment by xBajci** [comment]
@alank64 *base*  was a valid option and was [deprecated](https://github.com/senecajs/seneca-mesh/blob/master/mesh.js#L112) somewhere in the past.

**Comment by alank64** [comment]
@xBajci and others, my apologies, only jumped in at Seneca 3.x, in addition just to be clear: it's "isBase:..." and not "isbase: ..." just to be clear for others.
