### ISSUE TITLE
Monitor not working...

### ISSUE THREAD

**Issue by vforv** [senecajs/seneca-mesh#91]
My config:

```
var Seneca = require('seneca')

Seneca({tag: 'hex', log: 'silent'})
  .use('mesh', {
    monitor: true
  })
```

> error:
> 
>         throw new Error('[DEATH LOOP]')
>         ^
> 
> Error: [DEATH LOOP]
>     at Seneca.die (/home/master/Documents/Hapi/hapi-ts/node_modules/seneca/lib/common.js:276:15)
>     at Object.intern.handle_reply (/home/master/Documents/Hapi/hapi-ts/node_modules/seneca/seneca.js:1349:23)
>     at Object.act_tm [as ontm] (/home/master/Documents/Hapi/hapi-ts/node_modules/seneca/seneca.js:917:16)
>     at Timeout.timeout_check [as _onTimeout] (/home/master/Documents/Hapi/hapi-ts/node_modules/gate-executor/gate-executor.js:216:16)
>     at ontimeout (timers.js:365:14)
>     at tryOnTimeout (timers.js:237:5)
>     at Timer.listOnTimeout (timers.js:207:5)
> [nodemon] app crashed - waiting for file changes before starting...
> 
> 
>

**Comment by IRT-fbachmann** [comment]
Ditto, same error

**Comment by danielo515** [comment]
Environment ?
The Monitor requires some advanced terminal functionalities that may not work on certain environments like docker
