### ISSUE TITLE
seneca-mesh not working with overlay networks

### ISSUE THREAD

**Issue by rodmaz** [senecajs/seneca-mesh#98]
According to `seneca-mesh` documentation, it works with `overlay` networks but it apparently does not.

**Environment**
Developers environment, macOS Sierra, Docker for Mac (17.06.2-ce-mac27).

**Overlay network**
```
[
    {
        "Name": "developer-seneca-net",
        "Id": "fchha586es7cggjh5aywuc23a",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": null
    }
]
```

**Situation**

We are two containers on an `overlay` network. Container *B* (base) and container *S* (service). *S* points to the base by using the container B IP and port (39999).
Services DOES connect to the base as we can see in the logs. However after a timeout out, service gets disconnected due to a `gate-executor` `DEATH_LOOP`.

**Question:** _does the current version work with Docker overlay networks? _

```
/opt/project/node_modules/seneca/lib/common.js:276
        throw new Error('[DEATH LOOP]')
        ^

Error: [DEATH LOOP]
    at Seneca.die (/opt/project/node_modules/seneca/lib/common.js:276:15)
    at Object.intern.handle_reply (/opt/project/node_modules/seneca/seneca.js:1343:23)
    at Object.act_tm [as ontm] (/opt/project/node_modules/seneca/seneca.js:917:16)
    at Timeout.timeout_check [as _onTimeout] (/opt/project/node_modules/gate-executor/gate-executor.js:216:16)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
Waiting for the debugger to disconnect...
Debugger listening on ws://0.0.0.0:55376/20e1f9d6-356f-4567-913b-fe890f70c2a3
```

Service does found the base as we can see from the logs. However mesh base apparently tries to communicate back with the service in entries like these:

```
result: {
      "id": "attempt_delay:222,callmax:111111,hook:listen,host:0.0.0.0,ismesh:true,max_listen_attempts:11,model:consume,msgidlen:12,msgprefix:seneca_,path:/act,pin:cmd:recordEventApplicationDidOpen,role:analytics,port:57082,protocol:http,role:transport,serverOptions:[object Object],timeout:5555,type:web~vb6ugau4y16r/1504964905000/6/3.4.2/local~cmd:recordEventApplicationDidOpen,role:analytics~1504964907935"
    }
    plugin_name: "mesh"
    pattern: "hook:client,role:transport,type:web"
```

After a while, the service is disconnected with `DEATH_LOOP` error above.

**Comment by rodmaz** [comment]
OK, problem solved. In fact we have to use both the service **S** and base **B** current container IP when initializing `mesh` plugin. In our case we are using NodeJS IP module.

**Base**
```
  .use('mesh', {
    isbase: true,
    host: ip.address(),
    port: meshBasePort,
  })
```

**Service**
```
      seneca.use('mesh', {
        isBase: false,
        host: ip.address(),
        bases: [result.meshBaseAddress],
```

Hope this helps (lots of) people struggling with Seneca Mesh and Docker containers.

**Comment by danielo515** [comment]
Yes, it is very important to set the host as the detected ip. This should be added to the readme
